name: .NET CI Pipeline

on:
  push:
    branches: [ "MainBranch" ]
  pull_request:
    branches: [ "MainBranch" ]
  workflow_dispatch:

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish project
        run: dotnet publish --no-build --configuration Release -o publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish
